Repository edgebox-iot/api, pull requests merged in 2024-12, with the labels that each got.

#76 Release/1.3.0
  CHANGELOG.md
  src/public/assets/img/changelog-assets/screenshot_2024-12-06_1.jpeg
  src/public/assets/img/changelog-assets/screenshot_2024-12-06_2.jpeg
  src/public/assets/img/changelog-assets/screenshot_2024-12-06_3.jpeg
  src/public/assets/img/edgeapps/hello.png
  src/public/assets/img/edgeapps/paperlessngx.png
  src/public/assets/img/edgeapps/rocketchat.png
  src/public/assets/img/edgeapps/syncthing.png
  src/public/assets/img/edgeapps/test_banner.jpg
  src/src/Attribute/RunMiddleware.php
  src/src/Controller/ApiController.php
  src/src/Controller/BackupsController.php
  src/src/Controller/ChangelogController.php
  src/src/Controller/DocsController.php
  src/src/Controller/EdgeAppsController.php
  src/src/Controller/HomeController.php
  src/src/Controller/RegistrationController.php
  src/src/Controller/SecurityController.php
  src/src/Controller/SettingsController.php
  src/src/Controller/StorageController.php
  src/src/EventSubscriber/MiddlewareSubscriber.php
  src/src/Factory/TaskFactory.php
  src/src/Helper/BrowserDevHelper.php
  src/src/Helper/DashboardHelper.php
  src/src/Helper/UpdatesHelper.php
  src/src/Repository/OptionRepository.php
  src/templates/base.html.twig
  src/templates/blocks/_collapse_card.html.twig
  src/templates/pages/backups/index.html.twig
  src/templates/pages/changelog/1.2.html.twig
  src/templates/pages/changelog/1.3.html.twig
  src/templates/pages/docs/index.html.twig
  src/templates/pages/edgeapps/action.html.twig
  src/templates/pages/edgeapps/details.html.twig
  src/templates/pages/edgeapps/index.html.twig
  src/templates/pages/home/hello.html.twig
  src/templates/pages/home/index.html.twig
  src/templates/pages/registration/index.html.twig
  src/templates/pages/security/login.html.twig
  src/templates/pages/settings/action.html.twig
  src/templates/pages/settings/index.html.twig
  src/templates/pages/storage/device/new.html.twig
  src/templates/pages/storage/index.html.twig
  src/tests/Unit/Helper/EdgeAppsHelperTest.php
Labels: bug, enhancement

#77 Fix CI
  CHANGELOG.md
  src/src/Attribute/RunMiddleware.php
  src/src/Controller/ApiController.php
  src/src/Controller/BackupsController.php
  src/src/Controller/BaseController.php
  src/src/Controller/ChangelogController.php
  src/src/Controller/EdgeAppsController.php
  src/src/Controller/HomeController.php
  src/src/Controller/SettingsController.php
  src/src/EventSubscriber/MiddlewareSubscriber.php
  src/src/Factory/TaskFactory.php
  src/src/Helper/BrowserDevHelper.php
  src/src/Helper/DashboardHelper.php
  src/src/Helper/EdgeAppsHelper.php
  src/src/Helper/UpdatesHelper.php
  src/src/Repository/OptionRepository.php
  src/tests/Unit/Helper/EdgeAppsHelperTest.php
Labels: enhancement

#79 Add source code and composer dependencies to image build
  .github/workflows/build-push.yml
  .github/workflows/ci.yml
  CHANGELOG.md
  Dockerfile
  README.md
  docker-compose.yml
  edgebox-compose.yml
Labels: dependencies
